spring:
  application:
    name: simulator
  main:
    banner-mode: off
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
api:
  airport-service:
    url: ${AIRPORT_SERVICE:http://localhost:8080}
  flight-service:
    url: ${FLIGHT_SERVICE:http://localhost:8080}
    schedule-cron: '15 * * * * *'

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: full

logging:
  level:
    com.mikhailkarpov: debug
