spring:
  application:
    name: simulator
  main:
    banner-mode: off
  cloud:
    function:
      definition: flights
    stream:
      bindings:
        flights-in-0:
          destination: ${FLIGHTS_DESTINATION:flights}
          group: ${spring.application.name}
          consumer:
            max-attempts: 1
        airplanes-out-0:
          destination: ${AIRPLANES_DESTINATION:airplanes}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
api:
  airport-service:
    url: ${AIRPORT_SERVICE:http://localhost:8080}
  flight-service:
    url: ${FLIGHT_SERVICE:http://localhost:8080}
  airplane-service:
    schedule-cron: '2 * * * * *'

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: full

logging:
  level:
    root: warn
    com.mikhailkarpov: debug
