version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    hostname: api-gateway
    container_name: api-gateway
    environment:
      AIRPORT_SERVICE: http://airport-service:8080
      AIRPLANE_SERVICE: http://airplane-service:8080
      FLIGHT_SERVICE: http://flight-service:8080
    ports:
      - '8080:8080'

  airport-service:
    build: ./airport-service
    hostname: airport-service
    container_name: airport-service
    environment:
      SPRING_PROFILES_ACTIVE: demo

  flight-service:
    build: ./flight-service
    hostname: flight-service
    container_name: flight-service
    environment:
      SPRING_PROFILES_ACTIVE: demo
      AIRPORT_SERVICE: http://airport-service:8080
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      - kafka
    ports:
      - '8081:8080'

  airplane-service:
    build: ./airplane-service
    hostname: airplane-service
    container_name: airplane-service
    environment:
      AIRPORT_SERVICE: http://airport-service:8080
      FLIGHT_SERVICE: http://flight-service:8080
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      - redis
      - kafka
      - airport-service
      - flight-service

  redis:
    image: redis:6-alpine
    container_name: redis

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - '29092:29092'
