version: '3.8'

services:
  airport-service:
    build: ./airport-service
    container_name: airport-service
    environment:
      SPRING_PROFILES_ACTIVE: demo
    ports:
      - '8080:8080'

  flight-service:
    build: ./flight-service
    container_name: flight-service
    ports:
      - '8081:8080'
