spring:
  application:
    name: flight-service
  main:
    banner-mode: off
  jpa:
    open-in-view: false
  cloud:
    function:
      definition: airplane
    stream:
      bindings:
        airplane-in-0:
          destination: ${AIRPLANES_DESTINATION:airplanes}
          group: ${spring.application.name}
          consumer:
            max-attempts: 1
        airplaneCommand-out-0:
          destination: ${AIRPLANE_COMMANDS_DESTINATION:flights}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
logging:
  level:
    root: warn
    com.mikhailkarpov: debug
