spring:
  application:
    name: flight-service
  main:
    banner-mode: off
  jpa:
    open-in-view: false
  cloud:
    function:
      definition: airplane
    stream:
      bindings:
        airplane-in-0:
          destination: ${AIRPLANES_DESTINATION:airplanes}
          group: ${spring.application.name}
          consumer:
            max-attempts: 1
        airplaneCommand-out-0:
          destination: ${AIRPLANE_COMMANDS_DESTINATION:flights}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
api:
  airport-service:
    url: ${AIRPORT_SERVICE:http://localhost:8080}
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: full
logging:
  level:
    root: warn
    org.springframework.web: debug
    com.mikhailkarpov: info
